# requirements.yaml
dependencies:
- name: jupyterhub
  version: "0.9-e120fda"
  repository: 'https://jupyterhub.github.io/helm-chart/'
  import-values:
    - child: rbac
      parent: rbac
- name: prometheus
  version: 7.4.4
  repository: https://kubernetes-charts.storage.googleapis.com
- name: grafana
  version: 1.18.0
  repository: https://kubernetes-charts.storage.googleapis.com
