name: Check for new versions of the pangeo/base-notebook image

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.repository == 'pangeo-data/helm-chart'

    steps:
      - uses: actions/checkout@v2
      - name: Get latest Docker Hub tag
        id: latest_tag
        uses: jacobtomlinson/gha-get-docker-hub-tags@0.1.2
        with:
          org: "pangeo"
          repo: "base-notebook"
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@0.1.0
        with:
          include: "pangeo/"
          find: "tag: .* "
          replace: "tag: ${{ steps.latest_tag.outputs.tag }} "
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update pangeo/base-notebook version to ${{ steps.latest_tag.outputs.tag }}"
          title: "Update pangeo/base-notebook version to ${{ steps.latest_tag.outputs.tag }}"
          reviewers: "jacobtomlinson"
          branch: "upgrade-dask-version"
          body: |
            A new pangeo/base-notebook image version has been detected.

            Updated chart to use `${{ steps.latest_tag.outputs.tag }}`.
